### ISSUE TITLE
添加404错误页

### ISSUE THREAD

**Issue by xuexb** [jiandansousuo/jiandansousuo.com#2]
现在的比较丑... <https://jiandansousuo.com/404> 辛苦 @yugasun 来个简约风的404吧~

要兼容移动端哈~

**Comment by yugasun** [comment]
404页面如下：
![image](https://user-images.githubusercontent.com/8536173/30728526-437a9192-9f8b-11e7-98c3-d7c0bd864ec3.png)

**Comment by xuexb** [comment]
兼容下移动端吧? @yugasun
