### ISSUE TITLE
demo-pinyin-engine 搜索结果重复

### ISSUE THREAD

**Issue by xuexb** [jiandansousuo/jiandansousuo.com#3]
访问 <https://demo.jiandansousuo.com/pinyin-engine/example/> 输入`qhdx`时搜索结果重复, 如图:

![image](https://user-images.githubusercontent.com/3872051/30653650-4265eaea-9df1-11e7-817b-bbde19780a85.png)

**Comment by yugasun** [comment]
bug已修复，访问 https://demo.jiandansousuo.com/pinyin-engine/example/ 输入qhdx结果如图:
![image](https://user-images.githubusercontent.com/8536173/30676547-3386530c-9eb9-11e7-9fff-bff9bc8ffb71.png)

**Comment by xuexb** [comment]
@yugasun 赞~

后续如果有把握的修复, 你可以直接在 commit log 里带: `fix jiandansousuo/jiandansousuo.com#id` 自动修复

<https://help.github.com/articles/closing-issues-using-keywords/>
