### ISSUE TITLE
支持添加作者信息

### ISSUE THREAD

**Issue by xuexb** [jiandansousuo/jiandansousuo.com#4]
如: 在 `Front-matter` 里添加作者信息, 方便反馈问题. 也可以链接到对应的 Github 地址.

或者别的形式, 主要是想突出作者的署名.

感谢 @ddhhz 提这个非常赞的建议~

**Comment by yugasun** [comment]
@xuexb 可以再 `Front-matter` 里面添加 `author` 字段，那么这个字段应该是 `Github ID`，然后直接连接： `https://github.com/${author}`，你觉得如何？

PS: 主题中已具备 `from` 字段 - `转载 · 原文地址`

**Comment by yugasun** [comment]
已添加作者信息，`Front-matter`里面添加 author 字段，字段值为 `Github ID`，然后直接连接： `https://github.com/${author}`，如下图
![image](https://user-images.githubusercontent.com/8536173/30728382-3e0476d4-9f8a-11e7-9090-ac249bd64369.png)
